import type { Metadata, Viewport } from "next";
import { Fraunces, Plus_Jakarta_Sans, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import SiteHeader from "@/components/ui/SiteHeader";
import SiteFooter from "@/components/ui/SiteFooter";
import MobileTabBar from "@/components/ui/MobileTabBar";
import { api } from "@/lib/api";
import { LANG_BOOT_SCRIPT } from "@/lib/i18n";

/* Self-hosted via next/font — no render-blocking request to Google, no layout
   shift. Fraunces carries the editorial display voice and headline numerals;
   Plus Jakarta Sans the UI and body (Tokotype, a Jakarta foundry, originally
   drawn for the city's own identity); JetBrains Mono axis ticks, tables and
   readouts. */
const display = Fraunces({
  subsets: ["latin"],
  axes: ["SOFT", "WONK"],
  display: "swap",
  variable: "--font-display",
});

const sans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});

const mono = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mono",
});

export const metadata: Metadata = {
  // The real deployment. metadataBase resolves every relative canonical and
  // og:url below, so if it is wrong every share link and canonical is wrong —
  // it was still pointing at iklim.id, a domain this build does not serve.
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL ??
      "https://andifathulms.github.io/climatewatch",
  ),
  title: {
    default: "ClimateWatch — Climate Intelligence for Indonesia",
    template: "%s — ClimateWatch",
  },
  description:
    "ERA5 climate data for every year since 1950, for any Indonesian city. See how rainfall, temperature, and extreme weather have actually changed.",
  openGraph: {
    type: "website",
    siteName: "ClimateWatch",
    locale: "id_ID",
    url: "/",
    title: "ClimateWatch — Climate Intelligence for Indonesia",
    description:
      "ERA5 climate data for every year since 1950, for any Indonesian city, rendered as a Climate Fingerprint.",
    // Declared once on the root so every route inherits it — nested routes
    // set openGraph.title/description but not images, and an inherited image
    // is exactly what they want.
    //
    // A static file, not app/opengraph-image.tsx. That file convention works
    // under output:"export" and renders a good card, but it emits
    // `/opengraph-image` with NO file extension, which GitHub Pages serves as
    // application/octet-stream — and crawlers reject a card that is not typed
    // as an image. This PNG was generated by that same route and committed.
    images: [{ url: "/og.png", width: 1200, height: 630, alt: "ClimateWatch" }],
  },
  twitter: {
    card: "summary_large_image",
    images: ["/og.png"],
    title: "ClimateWatch — Climate Intelligence for Indonesia",
    description:
      "ERA5 climate data for every year since 1950, for any Indonesian city, rendered as a Climate Fingerprint.",
  },
  alternates: { canonical: "/" },
  // Android install manifest is a static file in public/. The app/manifest.ts
  // file-convention was avoided on purpose: its auto-injected <link> drops the
  // basePath (a Next quirk) and can't be overridden, which 404s on the
  // /climatewatch project path. A static file + explicit link sidesteps that.
  // apple-icon.png (app/) becomes the iOS home-screen icon; appleWebApp makes
  // "Add to Home Screen" open standalone with dark chrome.
  manifest: `${process.env.NEXT_PUBLIC_BASE_PATH ?? ""}/manifest.webmanifest`,
  appleWebApp: {
    capable: true,
    title: "ClimateWatch",
    statusBarStyle: "black",
  },
};

export const viewport: Viewport = {
  // The browser chrome/OS reads this before any stylesheet loads, so it has
  // to be a literal — it cannot reference var(--canvas) in tokens.css. Keep
  // this in sync by hand if --canvas ever changes (DESIGN.md §8).
  themeColor: "#12100c",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // The logo is the national warming stripes; everything else in the header
  // loads lazily. A missing file (fresh clone, no export yet) degrades to a
  // flat mark rather than failing every page.
  const national = await api
    .stripes()
    .then((s) => s.national.anomalies)
    .catch(() => [] as number[]);

  return (
    <html
      // Bahasa Indonesia by default; English via the ID/EN toggle. Both are
      // in the HTML (lib/i18n.tsx) and LANG_BOOT_SCRIPT flips these two
      // attributes before paint for a returning English reader.
      lang="id"
      data-lang="id"
      suppressHydrationWarning
      className={`${display.variable} ${sans.variable} ${mono.variable}`}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: LANG_BOOT_SCRIPT }} />
      </head>
      <body className="min-h-screen bg-canvas pb-16 antialiased lg:pb-0">
        {/* Skip link — the fingerprint is a long scroll target for keyboard users. */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-50 focus:rounded-full focus:bg-text-primary focus:px-4 focus:py-2 focus:text-sm focus:font-semibold focus:text-canvas"
        >
          <span data-l="id" lang="id">Lewati ke konten</span>
          <span data-l="en" lang="en">Skip to content</span>
        </a>

        <SiteHeader national={national} />

        <main id="main" className="mx-auto max-w-shell px-5 pb-24 sm:px-8">
          {children}
        </main>

        <SiteFooter />
        <MobileTabBar />
      </body>
    </html>
  );
}
