import type { Metadata, Viewport } from "next";
import { Fraunces, Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import SiteHeader from "@/components/ui/SiteHeader";
import SiteFooter from "@/components/ui/SiteFooter";

/* Self-hosted via next/font — no render-blocking request to Google, no layout
   shift. Fraunces carries the editorial display voice; Inter the UI; JetBrains
   Mono every climate number (tabular by default). */
const display = Fraunces({
  subsets: ["latin"],
  axes: ["SOFT", "WONK"],
  display: "swap",
  variable: "--font-display",
});

const sans = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});

const mono = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mono",
});

export const metadata: Metadata = {
  // The real deployment. metadataBase resolves every relative canonical and
  // og:url below, so if it is wrong every share link and canonical is wrong —
  // it was still pointing at iklim.id, a domain this build does not serve.
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL ??
      "https://andifathulms.github.io/climatewatch",
  ),
  title: {
    default: "ClimateWatch — Climate Intelligence for Indonesia",
    template: "%s — ClimateWatch",
  },
  description:
    "ERA5 climate data for every year since 1950, for any Indonesian city. See how rainfall, temperature, and extreme weather have actually changed.",
  openGraph: {
    type: "website",
    siteName: "ClimateWatch",
    locale: "en",
    url: "/",
    title: "ClimateWatch — Climate Intelligence for Indonesia",
    description:
      "ERA5 climate data for every year since 1950, for any Indonesian city, rendered as a Climate Fingerprint.",
    // Declared once on the root so every route inherits it — nested routes
    // set openGraph.title/description but not images, and an inherited image
    // is exactly what they want.
    //
    // A static file, not app/opengraph-image.tsx. That file convention works
    // under output:"export" and renders a good card, but it emits
    // `/opengraph-image` with NO file extension, which GitHub Pages serves as
    // application/octet-stream — and crawlers reject a card that is not typed
    // as an image. This PNG was generated by that same route and committed.
    images: [{ url: "/og.png", width: 1200, height: 630, alt: "ClimateWatch" }],
  },
  twitter: {
    card: "summary_large_image",
    images: ["/og.png"],
    title: "ClimateWatch — Climate Intelligence for Indonesia",
    description:
      "ERA5 climate data for every year since 1950, for any Indonesian city, rendered as a Climate Fingerprint.",
  },
  alternates: { canonical: "/" },
  // Android install manifest is a static file in public/. The app/manifest.ts
  // file-convention was avoided on purpose: its auto-injected <link> drops the
  // basePath (a Next quirk) and can't be overridden, which 404s on the
  // /climatewatch project path. A static file + explicit link sidesteps that.
  // apple-icon.png (app/) becomes the iOS home-screen icon; appleWebApp makes
  // "Add to Home Screen" open standalone with dark chrome.
  manifest: `${process.env.NEXT_PUBLIC_BASE_PATH ?? ""}/manifest.webmanifest`,
  appleWebApp: {
    capable: true,
    title: "ClimateWatch",
    statusBarStyle: "black",
  },
};

export const viewport: Viewport = {
  // The browser chrome/OS reads this before any stylesheet loads, so it has
  // to be a literal — it cannot reference var(--canvas) in tokens.css. Keep
  // this in sync by hand if --canvas ever changes (DESIGN.md §8).
  themeColor: "#12100c",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      // Every string in this product is English. lang="id" told screen
      // readers to pronounce English text with Indonesian phonetics (WCAG
      // 3.1.1) and told search engines this was Indonesian-language content.
      // JUDGEMENT CALL: the audience is Indonesian and Bahasa i18n is PRD
      // Phase 5 — this line goes back to "id" the day translated content
      // ships, and per-locale lang belongs on the routes at that point.
      lang="en"
      className={`${display.variable} ${sans.variable} ${mono.variable}`}
    >
      <body className="min-h-screen bg-canvas antialiased">
        {/* Skip link — the fingerprint is a long scroll target for keyboard users. */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-50 focus:rounded-full focus:bg-text-primary focus:px-4 focus:py-2 focus:text-sm focus:font-semibold focus:text-canvas"
        >
          Skip to content
        </a>

        <SiteHeader />

        <main id="main" className="mx-auto max-w-shell px-5 pb-24 sm:px-8">
          {children}
        </main>

        <SiteFooter />
      </body>
    </html>
  );
}
