# Generated by Django 5.0.6 on 2026-07-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='climateannual',
            name='max_consecutive_hot_days',
            field=models.IntegerField(default=0, help_text='Longest streak of consecutive days with temp_max > 35C'),
        ),
    ]
