# Generated by Django 5.0.6 on 2026-08-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0002_climateannual_max_consecutive_hot_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='climateannual',
            name='hot_days_local',
            field=models.IntegerField(default=0, help_text="Days above the region's hot_day_threshold_c"),
        ),
        migrations.AddField(
            model_name='climatemonthly',
            name='hot_days_local',
            field=models.IntegerField(default=0, help_text="Days above the region's hot_day_threshold_c"),
        ),
        migrations.AlterField(
            model_name='climatemonthly',
            name='hot_days',
            field=models.IntegerField(default=0, help_text='Days with temp_max > 35C (absolute, cross-city comparable)'),
        ),
    ]
