# Generated by Django 5.0.6 on 2026-08-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0003_climateannual_hot_days_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climateannual',
            name='max_consecutive_hot_days_local',
            field=models.IntegerField(default=0, help_text='Longest streak of consecutive days above hot_day_threshold_c'),
        ),
    ]
