# Generated by Django 5.0.6 on 2026-09-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0004_climateannual_max_consecutive_hot_days_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='climateannual',
            name='avg_apparent_temp_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='climatedaily',
            name='apparent_temp_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='climatemonthly',
            name='avg_apparent_temp_max',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
