# Generated by Django 5.0.6 on 2026-09-27 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0005_apparent_temp_max'),
        ('regions', '0002_indonesiaregion_hot_day_threshold_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
                ('avg_temp_max', models.FloatField(blank=True, null=True)),
                ('total_precipitation', models.FloatField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='regions.indonesiaregion')),
            ],
            options={
                'ordering': ['model', 'year'],
            },
        ),
        migrations.AddConstraint(
            model_name='climateprojection',
            constraint=models.UniqueConstraint(fields=('region', 'model', 'year'), name='uniq_projection'),
        ),
    ]
