# Generated by Django 5.0.6 on 2026-08-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indonesiaregion',
            name='hot_day_threshold_c',
            field=models.FloatField(blank=True, help_text='95th percentile of 1951-1980 daily temp_max (°C).', null=True),
        ),
    ]
